dle/api/urls.py
from django.urls import path

from . import views


app_name = "api"

urlpatterns = [
    path("v1/searchkit/_msearch", views.searchkit, name="searchkit"),
    # This is used so we can reverse it in search/views.py for the search.html context
    path("v1/searchkit", views.searchkit, name="searchkit_root"),
    path("v1/vectorize", views.vectorize, name="vectorize"),
    path("v1/search", views.search, name="search"),
    path("v1/search_label", views.search_label, name="search_label")
]

dle/data/urls.py
from django.urls import path

from . import views


app_name = "data"
urlpatterns = [
    path("", views.index, name="index"),
    path(
        "single_label_view/<int:drug_label_id>", views.single_label_view, name="single_label_view"
    ),
    path(
        "single_label_view/<int:drug_label_id>, <str:search_text>",
        views.single_label_view,
        name="single_label_view",
    ),
    path("visualizations", views.visualizations, name="dataviz"),
    path("search_label_htmx", views.search_label_htmx, name="search_label_htmx"),
]

dle/dle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpRequest
from django.shortcuts import redirect
from django.urls import include, path


# from django.contrib import admin


def redirect_from_root_view(request: HttpRequest):
    """Redirects requests to rootpath to the search endpoint."""
    return redirect("/search")


urlpatterns = [
    # path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("data/", include("data.urls")),
    path("", redirect_from_root_view),
    path("search/", include("search.urls")),
    path("compare/", include("compare.urls")),
    path("api/", include("api.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dle/search/urls.py
from django.urls import path

from . import views


app_name = "search"

urlpatterns = [
    path("", views.index, name="index"),
    path("results", views.list_search_results, name="list_search_results"),
    path("es_search", views.es_search, name="es_search"),
]

dle/users/urls.py
from django.urls import path

from . import views


app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("my_labels/", views.my_labels_view, name="my_labels"),
    path("my_labels/create/", views.create_my_label, name="create_my_label"),
    path("saved_searches/create/", views.create_saved_search, name="create_my_saved_search"),
]

dle/search/models.py
from typing import NamedTuple, Optional

from django.http import QueryDict


"""
/search/results?search_text=blandit&select_agency=fda&manufacturer_input=gsk&marketing_category_input=&country_input=&generic_name_input=&brand_name_input=&ndc_input=
"""


class SearchRequest(NamedTuple):
    search_text: str
    select_section: str
    select_agency: Optional[str] = None
    manufacturer_input: Optional[str] = None
    marketing_category_input: Optional[str] = None
    generic_name_input: Optional[str] = None
    brand_name_input: Optional[str] = None
    ndc_input: Optional[str] = None
    all_label_versions: Optional[bool] = False

    @classmethod
    def from_search_query_dict(cls, search_query_dict: QueryDict) -> "SearchRequest":
        cls_params = [search_query_dict.get(field, "").lower() for field in cls._fields]

        return cls._make(cls_params)

    @classmethod
    def build_url_query(cls, search_request: "SearchRequest") -> str:
        search_request_dict = search_request._asdict()
        return "".join([f"&{field}={search_request_dict[field]}" for field in cls._fields])


class InvalidSearchRequest(Exception):
    pass

dle/search/views.py
from typing import List, Set, Tuple

from django.core.paginator import Paginator
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.cache import cache_page

from data.models import DrugLabel
from search.models import SearchRequest
from users.forms import SavedSearchForm
from users.models import MyLabel

from . import services as SearchService
from .services import get_type_ahead_mapping


# NOTE comment out cache decorators when doing development to view updates to your front-end templates.
def index(request: HttpRequest) -> HttpResponse:
    """Landing page search view."""
    # turn off caching for authenticated users
    if request.user and request.user.is_authenticated:
        return index_impl(request)
    return index_cached(request)


@cache_page(60 * 60)
def index_cached(request: HttpRequest) -> HttpResponse:
    return index_impl(request)


def index_impl(request: HttpRequest) -> HttpResponse:
    TYPE_AHEAD_MAPPING = get_type_ahead_mapping()
    context = {
        "type_ahead_manufacturer": TYPE_AHEAD_MAPPING["manufacturers"],
        "type_ahead_generic_name": TYPE_AHEAD_MAPPING["generic_name"],
        "type_ahead_brand_name": TYPE_AHEAD_MAPPING["brand_name"],
        "type_ahead_section_name": TYPE_AHEAD_MAPPING["section_name"],
    }

    return render(request, "search/search_landing/search_landing.html", context)


def list_search_results(request: HttpRequest) -> HttpResponse:
    if request.user and request.user.is_authenticated:
        return list_search_results_impl(request)
    return list_search_results_cached(request)


@cache_page(60 * 60)
def list_search_results_cached(request: HttpRequest) -> HttpResponse:
    return list_search_results_impl(request)


def list_search_results_impl(request: HttpRequest) -> HttpResponse:
    """Search results list view
    Args:
        request (HttpRequest): GET request with search text and multiple boolean flags.
    Returns:
        HttpResponse: Search results view with highlighted text
    """
    search_request_object = SearchService.validate_search(request.GET)
    search_query_url = SearchRequest.build_url_query(search_request=search_request_object)
    results = SearchService.process_search(search_request_object, request.user)
    processed_labels: Set[int] = set()
    search_results_to_display: List[Tuple[DrugLabel, str]] = []
    for result in results:
        if result.id not in processed_labels:
            search_results_to_display.append(
                SearchService.build_search_result(result, search_request_object.search_text)
            )
            processed_labels.add(result.id)

    TYPE_AHEAD_MAPPING = get_type_ahead_mapping()
    paginator = Paginator(search_results_to_display, 20)  # show 20 results per pagination
    page_number = request.GET.get("page", "1")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        "search_query_url": search_query_url,
        "search_request_object": search_request_object,
        "type_ahead_manufacturer": TYPE_AHEAD_MAPPING["manufacturers"],
        "type_ahead_generic_name": TYPE_AHEAD_MAPPING["generic_name"],
        "type_ahead_brand_name": TYPE_AHEAD_MAPPING["brand_name"],
        "type_ahead_section_name": TYPE_AHEAD_MAPPING["section_name"],
    }

    return render(request, "search/search_results/search_results.html", context=context)


def es_search(request: HttpRequest) -> HttpResponse:
    """Search results list view"""
    form = SavedSearchForm()
    if request.user.is_authenticated:
        my_labels = MyLabel.objects.filter(user=request.user).all()

        # for my_label in my_labels:
        #     drug_label = get_object_or_404(DrugLabel, pk=drug_label_id)

    else:
        my_labels = []

    SEARCHKIT_SERVICE = f"{reverse('api:searchkit_root')}"
    VECTORIZE_SERVICE = f"{reverse('api:vectorize')}"

    context = {
        "SEARCHKIT_SERVICE": SEARCHKIT_SERVICE,
        "VECTORIZE_SERVICE": VECTORIZE_SERVICE,
        "form": form,
        "my_labels": my_labels,
    }

    return render(request, "search/elastic/search.html", context=context)

dle/search/templates/search/base 2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <title>{% block title %}DLE{% endblock title %}</title>
        <link rel="icon" href="{% static 'search/dle-logo.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{% static 'search/styles.css' %}" rel="stylesheet">

        {% block head %}{% endblock %}
    </head>
    <body>
        {% include 'search/header.html' %}
        <div class="content">{% block content %}{% endblock %}</div>
        {% block footer_scripts %}{% endblock %}
    </body>
</html>

dle/search/templates/search/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <title>{% block title %}SearchRx{% endblock title %}</title>
        <link rel="icon" href="{% static 'search/gdle-logo.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{% static 'search/styles.css' %}" rel="stylesheet">

        <!-- vendor JS -->
        {% load django_htmx %}
        <script src="{% static 'js/htmx/htmx.min.js' %}" defer></script>
        {% django_htmx_script %}

        <!-- CSRF token for HTMX -->
        <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

        {% block head %}{% endblock %}
    </head>
    <body>
        {% include 'search/header.html' %}
        <div class="content">{% block content %}{% endblock %}</div>
        {% block footer_scripts %}{% endblock %}
    </body>
</html>

dle/search/templates/search/header 2.html
{% block header %}
 <header class="header">
     <div class="brand">
        <a class="brand-logo" href="{% url 'search:index' %}">Drug Label Explorer</a>
     </div>
     <div>
         <ul class="nav">
            <!--navigation tool for moving to different pages-->
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:my_labels' %}"> My Labels</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            {% endif %}
        </ul>
     </div>
 </header>
 <br>
{% endblock %}

dle/search/templates/search/header.html
{% block header %}
 <header class="header">
     <div class="brand">
        <a class="brand-logo" href="{% url 'search:index' %}">SearchRx</a>
     </div>
     <div>
         <ul class="nav">
            <!--navigation tool for moving to different pages-->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'search:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'data:dataviz' %}">Visualizations</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:my_labels' %}"> My Labels</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            {% endif %}
        </ul>
     </div>
 </header>
 <br>
{% endblock %}