dle/api/urls.py
from django.urls import path

from . import views


app_name = "api"

urlpatterns = [
    path("v1/searchkit/_msearch", views.searchkit, name="searchkit"),
    # This is used so we can reverse it in search/views.py for the search.html context
    path("v1/searchkit", views.searchkit, name="searchkit_root"),
    path("v1/vectorize", views.vectorize, name="vectorize"),
    path("v1/search", views.search, name="search"),
    path("v1/search_label", views.search_label, name="search_label")
]

dle/data/urls.py
from django.urls import path

from . import views


app_name = "data"
urlpatterns = [
    path("", views.index, name="index"),
    path(
        "single_label_view/<int:drug_label_id>", views.single_label_view, name="single_label_view"
    ),
    path(
        "single_label_view/<int:drug_label_id>, <str:search_text>",
        views.single_label_view,
        name="single_label_view",
    ),
    path("visualizations", views.visualizations, name="dataviz"),
    path("search_label_htmx", views.search_label_htmx, name="search_label_htmx"),
]

dle/dle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpRequest
from django.shortcuts import redirect
from django.urls import include, path


# from django.contrib import admin


def redirect_from_root_view(request: HttpRequest):
    """Redirects requests to rootpath to the search endpoint."""
    return redirect("/search")


urlpatterns = [
    # path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("data/", include("data.urls")),
    path("", redirect_from_root_view),
    path("search/", include("search.urls")),
    path("compare/", include("compare.urls")),
    path("api/", include("api.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dle/users/urls.py
from django.urls import path

from . import views


app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("my_labels/", views.my_labels_view, name="my_labels"),
    path("my_labels/create/", views.create_my_label, name="create_my_label"),
    path("saved_searches/create/", views.create_saved_search, name="create_my_saved_search"),
]

dle/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

from data.models import DrugLabel


class User(AbstractUser):
    pass


class MyLabel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    drug_label = models.ForeignKey(DrugLabel, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, db_index=True)
    file = models.FileField(upload_to="my_labels/", max_length=255)
    is_successfully_parsed = models.BooleanField(default=False, db_index=True)

    def __str__(self):
        return (
            f"MyLabel: {self.id}, "
            f"user: {self.user}, "
            f"drug_label: {self.drug_label}, "
            f"name: {self.name}, "
            f"file.name: {self.file.name}, "
            f"is_successfully_parsed: {self.is_successfully_parsed}"
        )


class SavedSearch(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.TextField()
    name = models.CharField(max_length=255, db_index=True)

dle/users/forms.py
from django import forms

from data.models import SOURCES


class MyLabelForm(forms.Form):
    name = forms.CharField(label="Drug Label Name", max_length=255, required=True)
    file = forms.FileField(label="Drug Label File", required=True)
    source = forms.ChoiceField(choices=SOURCES, required=True)
    product_name = forms.CharField(label="Product Name", max_length=255, required=True)
    generic_name = forms.CharField(label="Generic name", max_length=255, required=True)
    product_number = forms.CharField(label="Product Number", max_length=255, required=True)
    marketer = forms.CharField(label="Marketer", max_length=255, required=True)


class SavedSearchForm(forms.Form):
    name = forms.CharField(label="Search Name", max_length=255, required=True)
    url = forms.CharField(label="Url", max_length=400, required=True, widget=forms.HiddenInput())

dle/users/views.py
import datetime as dt

from django.core import management
from django.db import IntegrityError, connection
from django.shortcuts import redirect, render
from django.urls import reverse

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from data.models import DrugLabel

from .forms import MyLabelForm, SavedSearchForm
from .models import MyLabel, SavedSearch, User


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return redirect(reverse("search:index"), request)

        else:
            return render(
                request,
                "users/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "users/login.html")


@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse("users:login"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "users/register.html", {"message": "Passwords must match."})

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "users/register.html", {"message": "Username already taken."})
        login(request, user)
        return redirect(reverse("search:index"), request)
    else:
        return render(request, "users/register.html")


@login_required
def my_labels_view(request, msg=None):
    # create a blank form for the user to create a new my_label
    form = MyLabelForm()
    # get a list of the user's MyLabels
    # note, could have performance issues if user has a "lot" of labels
    my_labels = MyLabel.objects.filter(user=request.user).all()
    saved_searches = SavedSearch.objects.filter(user=request.user).all()

    context = {
        "form": form,
        "my_labels": my_labels,
        "message": msg,
        "saved_searches": saved_searches,
    }
    return render(request, "users/my_labels.html", context)


@login_required
def create_saved_search(request):
    """Accepts a request for a user to create saved search record"""
    if request.method == "POST":
        form = SavedSearchForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data["url"]
            name = form.cleaned_data["name"]

            saved_search = SavedSearch(
                url=url,
                name=name,
                user=request.user,
            )

            saved_search.save()

            return redirect(reverse("users:my_labels"))


@login_required
def create_my_label(request):
    """Accepts a request for a user to create a new MyLabel"""
    if request.method == "POST":
        form = MyLabelForm(request.POST, request.FILES)

        if form.is_valid():
            file_name_suffix = form.cleaned_data["file"].name.split(".")[-1]
            supported_filetypes = ["pdf", "xml"]
            if file_name_suffix not in supported_filetypes:
                msg = "File must be one of: " + str(supported_filetypes)
                return my_labels_view(request, msg)

            if form.cleaned_data["source"] == "EMA" and file_name_suffix != "pdf":
                msg = "Only pdf files are supported for EMA drug labels"
                return my_labels_view(request, msg)

            if form.cleaned_data["source"] == "FDA" and file_name_suffix != "xml":
                msg = "Only xml files are supported for FDA drug labels"
                return my_labels_view(request, msg)

            # create a DrugLabel object for the uploaded label
            dl = DrugLabel(
                source=form.cleaned_data["source"],
                product_name=form.cleaned_data["product_name"],
                generic_name=form.cleaned_data["generic_name"],
                version_date=dt.datetime.now(),
                source_product_number="my_label_" + form.cleaned_data["product_number"],
                marketer=form.cleaned_data["marketer"],
            )
            try:
                dl.save()
            except IntegrityError:
                msg = "Unable to add the drug label. Try changing the product number."
                return my_labels_view(request, msg)

            # create the MyLabel object referencing the DrugLabel
            ml = MyLabel(
                user=request.user,
                drug_label=dl,
                name=form.cleaned_data["name"],
                file=request.FILES["file"],
            )
            ml.save()

            # process the file
            # send to load_fda_data or load_ema_data
            # --type my_label --my_label_id ml.id
            command = "load_fda_data" if form.cleaned_data["source"] == "FDA" else "load_ema_data"
            management.call_command(command, type="my_label", my_label_id=ml.id)

            # add to latest_drug_labels
            sql = f"INSERT INTO latest_drug_labels VALUES ({dl.id})"
            with connection.cursor() as cursor:
                cursor.execute(sql)

    return redirect(reverse("users:my_labels"))

dle/users/templates/users/login 2.html
{% extends "search/base.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm">
                <div class="login">
                    <h2>Log in</h2><br>
             
                   {% if message %}
                     <div>
                        {{ message }}
                     </div>
                   {% endif %}
             
                   <form action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}
             
                         <div class="form-group">
                            <input autofocus class="row form-control" type="text" name="username" placeholder="Username">
                         </div>
             
                         <div class="form-group">
                             <input class="row form-control" type="password" name="password" placeholder="Password">
                         </div>
             
                         <input class="btn btn-primary" type="submit" value="Login">
                     </form><br>
             
                     Don't have an account? <a href="{% url 'users:register' %}">Register here.</a>
                 </div>                
            </div>
            <div class="col-sm"></div>
        </div>
    </div>

{% endblock %}

dle/users/templates/users/login.html
{% extends "search/base.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm">
                <div class="login">
                    <h2>Log in</h2><br>
             
                   {% if message %}
                     <div>
                        {{ message }}
                     </div>
                   {% endif %}
             
                   <form action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}
             
                         <div class="form-group">
                            <input autofocus class="row form-control" type="text" name="username" placeholder="Username">
                         </div>
             
                         <div class="form-group">
                             <input class="row form-control" type="password" name="password" placeholder="Password">
                         </div>
             
                         <input class="btn btn-primary" type="submit" value="Login">
                     </form><br>
             
                     Don't have an account? <a href="{% url 'users:register' %}">Register here.</a>
                 </div>                
            </div>
            <div class="col-sm"></div>
        </div>
    </div>

{% endblock %}

dle/users/templates/users/my_labels 2.html
{% extends "search/base.html" %}

{% block title %}MyLabels{% endblock title %}

{% block content %}

<h4>Upload Label</h4>
<form method="post" action="/users/my_labels/create/" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <input class="btn btn-primary" type="submit" value="Submit">
</form>
<br><br><br><br>

{% if message %}
<div>
   {{ message }}
</div>
{% endif %}

<h4>My Labels</h4>
    {% for my_label in my_labels %}
        <p><h5>{{ my_label.name }}</h5></p>
        <a href="{% url 'data:single_label_view' drug_label_id=my_label.drug_label.id %}">Link</a><br>
        <p>Successfully parsed: {{ my_label.is_successfully_parsed }}</p>
    {% endfor %}

{% endblock %}

dle/users/templates/users/my_labels.html
{% extends "search/base.html" %}

{% block title %}MyLabels{% endblock title %}

{% block content %}

<h4>Upload Label</h4>
<form method="post" action="/users/my_labels/create/" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <input class="btn btn-primary" type="submit" value="Submit">
</form>
<br><br><br><br>

{% if message %}
<div>
   {{ message }}
</div>
{% endif %}

<h4>My Labels</h4>
    {% for my_label in my_labels %}
        <p><h5>{{ my_label.name }}</h5></p>
        <a href="{% url 'data:single_label_view' drug_label_id=my_label.drug_label.id %}">Link</a><br>
        <p>Successfully parsed: {{ my_label.is_successfully_parsed }}</p>
    {% endfor %}

<h4>My Saved Searches</h4>
{% for search in saved_searches %}
    <a href="{{ search.url }}">{{ search.name }}</a><br>
{% endfor %}


{% endblock %}

dle/users/templates/users/register 2.html
{% extends "search/base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm">
            <div class="register">
                <h2>Register</h2>
                <br>
                Welcome to Drug Label Explorer! Please register here.
                <br> <br>
        
                {% if message %}
                    <div>{{ message }}</div>
                {% endif %}
        
                <form action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
        
                    <div class="form-group">
                        <input class="row form-control" autofocus type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input class="row form-control" type="email" name="email" placeholder="Email Address">
                    </div>
                    <div class="form-group">
                        <input class="row form-control" type="password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <input class="row form-control" type="password" name="confirmation" placeholder="Confirm Password">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Register">
                </form> <br>
        
                Already have an account? <a href="{% url 'users:login' %}">Log In here.</a>     
            </div>
        </div>
        <div class="col-sm"></div>
    </div>
</div>
    

{% endblock %}

dle/users/templates/users/register.html
{% extends "search/base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm">
            <div class="register">
                <h2>Register</h2>
                <br>
                Welcome to SearchRx! Please register here.
                <br> <br>
        
                {% if message %}
                    <div>{{ message }}</div>
                {% endif %}
        
                <form action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
        
                    <div class="form-group">
                        <input class="row form-control" autofocus type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input class="row form-control" type="email" name="email" placeholder="Email Address">
                    </div>
                    <div class="form-group">
                        <input class="row form-control" type="password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <input class="row form-control" type="password" name="confirmation" placeholder="Confirm Password">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Register">
                </form> <br>
        
                Already have an account? <a href="{% url 'users:login' %}">Log In here.</a>     
            </div>
        </div>
        <div class="col-sm"></div>
    </div>
</div>
    

{% endblock %}